// GENERATED by `uv run python -m pipeline.thermal.grammar`. Do not edit.
//
// The grammar that constrains stage 1 extraction, generated from
// config/condition-map.yaml. The model cannot emit a condition term this file
// does not list, because no token sequence spelling one is reachable under the
// grammar. That is the difference between a schema the model is asked to
// follow and a schema it is unable to violate.
//
// Regenerate after editing the condition map. app/tests/unit/extraction.test.ts
// asserts the two stay in step.

/** Applied when the user states nothing. The thermal layer is off. */
export const CONDITION_DEFAULTS: Record<string, unknown> = {
  "heat_aware": false,
  "sun_inflation": 0.0,
  "router_profile": "generic_pedestrian",
  "max_continuous_exposure_min": null,
  "prefer_indoor_waiting": false
};

/**
 * What each condition term implies for routing, from config/condition-map.yaml.
 *
 * The scale these sit on is empirical: Melnikov et al. (2022) estimate a
 * population mean sun inflation of 0.16 and individual values to 0.84. Where a
 * given condition sits on that scale is a design judgement, and the YAML says
 * so in as many words. Read a number here as "where we put this condition on a
 * measured scale", not as "what was measured for this condition".
 */
export const CONDITION_EFFECTS: Record<string, Record<string, unknown>> = {
  "heat_sensitivity_moderate": {
    "heat_aware": true,
    "sun_inflation": 0.16
  },
  "heat_sensitivity_high": {
    "heat_aware": true,
    "sun_inflation": 0.63,
    "max_continuous_exposure_min": 10,
    "prefer_indoor_waiting": true
  },
  "impaired_sweating": {
    "heat_aware": true,
    "sun_inflation": 0.84,
    "max_continuous_exposure_min": 7,
    "prefer_indoor_waiting": true
  },
  "cardiovascular_strain": {
    "heat_aware": true,
    "sun_inflation": 0.63,
    "max_continuous_exposure_min": 8,
    "prefer_indoor_waiting": true
  },
  "respiratory_limitation": {
    "heat_aware": true,
    "sun_inflation": 0.4,
    "max_continuous_exposure_min": 12,
    "prefer_indoor_waiting": true
  },
  "uv_sensitivity_high": {
    "heat_aware": true,
    "sun_inflation": 0.63,
    "prefer_indoor_waiting": true
  },
  "medication_heat_risk": {
    "heat_aware": true,
    "sun_inflation": 0.4,
    "max_continuous_exposure_min": 12,
    "prefer_indoor_waiting": true
  },
  "older_adult": {
    "heat_aware": true,
    "sun_inflation": 0.63,
    "max_continuous_exposure_min": 12,
    "prefer_indoor_waiting": true
  },
  "young_child": {
    "heat_aware": true,
    "sun_inflation": 0.4,
    "router_profile": "generic_pedestrian",
    "max_continuous_exposure_min": 12
  },
  "pregnancy": {
    "heat_aware": true,
    "sun_inflation": 0.4,
    "max_continuous_exposure_min": 12,
    "prefer_indoor_waiting": true
  },
  "mobility_wheelchair": {
    "router_profile": "manual_wheelchair"
  },
  "mobility_slow": {
    "router_profile": "generic_pedestrian",
    "max_continuous_exposure_min": 12
  },
  "low_vision": {
    "router_profile": "low_vision"
  }
};

/** Version of config/condition-map.yaml these were generated from. */
export const CONDITION_MAP_VERSION = 4;

/** What the condition map says it does not cover. Surfaced in the interface. */
export const UNMODELLED: string[] = [
  "Humidity. Evaporative cooling fails as humidity rises, and NYC summers are humid. The proxy MRT layer has no humidity term.",
  "Wind. Convective cooling varies street by street and is not modelled.",
  "Air quality. Ozone and PM2.5 rise with heat and drive respiratory risk.",
  "Personal acclimatisation, fitness, hydration and clothing.",
  "Time of day beyond the single precomputed hour the grid was built for.",
  "Indoor conditions at the destination, including whether its cooling works.",
  "Cumulative exposure across a whole day, or across consecutive days."
];
