// GENERATED by `uv run python -m pipeline.thermal.profiles`. Do not edit.
//
// The thermal cost parameters, derived from published sources by
// pipeline/thermal/thresholds.py. They exist in TypeScript as well as in the
// routing profiles because transit waits are priced here, where the WASM cost
// tree never runs. app/tests/unit/thermal.test.ts asserts the two agree.

/** Mean radiant temperature (C) of full building shade at the reference meteorology. */
export const MRT_SHADE_C = 33.01;

/** Mean radiant temperature (C) of open full sun at the same reference meteorology. */
export const MRT_SUN_C = 61.8;

/**
 * Extra cost at full sun exposure, as a fraction of distance: beta - 1.
 *
 * Melnikov et al. (2022), Scientific Reports 12:2441, estimate a population
 * mean beta of 1.16 from 408 observed pedestrian path choices.
 */
export const SUN_INFLATION_DEFAULT = 0.16;

/** Melnikov et al. (2022) observed individual maximum, beta = 1.84. */
export const SUN_INFLATION_SENSITIVE = 0.84;

/** Basu et al. (2024) Boston revealed preference, converted to the same units. */
export const SUN_INFLATION_BASU = 0.6332;

/** Official UTCI thermal stress boundaries, inverted to mean radiant temperature. */
export const UTCI_CATEGORY_MRT_C: Record<string, number | string> = {
  "extreme heat stress": 94.64,
  "very strong heat stress": 61.4,
  "strong heat stress": 33.32,
  "moderate heat stress": "always exceeded",
  "no thermal stress": "always exceeded"
};

/** The weather every number above is conditioned on. */
export const REFERENCE_METEOROLOGY = {
  "label": "NWS New York Heat Advisory threshold, NOAA 1991-2020 normals at LaGuardia",
  "air_temp_c": 34.3,
  "vapour_pressure_hpa": 19.7,
  "wind_10m_ms": 5.41,
  "sources": [
    "NWS New York (OKX) Extreme Heat: Heat Advisory at heat index 95 to 99 F",
    "NOAA NCEI 1991-2020 hourly normals, USW00014732, 21 Jul 15:00 local"
  ]
} as const;
