// Thermal routing arguments and the cost the router charges for heat.
//
// The cost is a distance-inflating coefficient on thermal exposure, after
// Melnikov et al. (2022), Scientific Reports 12:2441, who estimate pedestrian
// route choice in heat from 408 observed path choices as
//
//     c = beta * a_sun + a_shade
//
// with a population mean beta of 1.16: a metre walked in full sun is felt as
// 1.16 metres walked in shade. This generalises that binary split to the
// continuous exposure field the thermal grid produces:
//
//     cost = length * (1 + (beta - 1) * exposure)
//     exposure = clamp((mrt - MRT_SHADE_C) / (MRT_SUN_C - MRT_SHADE_C), 0, 1)
//
// Every constant comes from thermal-constants.ts, which is generated by
// pipeline/thermal/thresholds.py from published sources. None is chosen here.
//
// Two properties worth stating plainly, because both are easy to lose:
//
// The zero point is full shade, not thermal comfort. An edge outside every
// surveyed neighbourhood has no mrt attribute and is charged nothing, so
// anchoring the zero at full shade makes an unsurveyed edge cost the same as a
// fully shaded one. Anchoring at a comfort threshold instead would charge
// every surveyed edge and pay the router to leave coverage.
//
// The cost is not banded on UTCI thermal stress categories. At NYC conditions
// dUTCI/dMRT is about 0.21, so the roughly 29 K between full shade and full
// sun is only about 6 K of UTCI, and a whole neighbourhood falls inside one or
// two categories. Categories describe danger well and discriminate routes
// badly; they are used for labelling only.

import {
  MRT_SHADE_C,
  MRT_SUN_C,
  SUN_INFLATION_DEFAULT,
  SUN_INFLATION_SENSITIVE,
  UTCI_CATEGORY_MRT_C,
} from './thermal-constants';

export {
  MRT_SHADE_C,
  MRT_SUN_C,
  SUN_INFLATION_DEFAULT,
  SUN_INFLATION_SENSITIVE,
  UTCI_CATEGORY_MRT_C,
};

export type ThermalArgs = {
  /** Off reproduces the pre-thermal router exactly. */
  heat_aware: boolean;
  /**
   * beta - 1: the extra cost at full sun exposure, as a fraction of distance.
   * Defaults to the Melnikov population mean. config/condition-map.yaml moves
   * it per person rather than adding a routing profile.
   */
  sun_inflation?: number;
  /** Mean radiant temperature (C) treated as full shade. */
  mrt_shade?: number;
  /** Mean radiant temperature (C) treated as full sun. */
  mrt_sun?: number;
};

export const THERMAL_OFF: ThermalArgs = { heat_aware: false };
export const THERMAL_ON: ThermalArgs = {
  heat_aware: true,
  sun_inflation: SUN_INFLATION_DEFAULT,
};

/**
 * Serialise for the WASM `args_json` parameter. Null when heat awareness is
 * off, so the router takes its default path and the profile's own default of
 * `sun_inflation = 0` applies.
 */
export function thermalArgsJSON(t: ThermalArgs | undefined): string | null {
  if (!t || !t.heat_aware) return null;
  return JSON.stringify({
    sun_inflation: t.sun_inflation ?? SUN_INFLATION_DEFAULT,
    ...(t.mrt_shade === undefined ? {} : { mrt_shade: t.mrt_shade }),
    ...(t.mrt_sun === undefined ? {} : { mrt_sun: t.mrt_sun }),
  });
}

/**
 * Position of a mean radiant temperature between the shade and sun anchors,
 * clamped to [0, 1]. Returns 0 for an unknown temperature.
 */
export function exposureFraction(
  mrtC: number | null | undefined,
  args?: ThermalArgs,
): number {
  if (mrtC === null || mrtC === undefined || !Number.isFinite(mrtC)) return 0;
  const shade = args?.mrt_shade ?? MRT_SHADE_C;
  const sun = args?.mrt_sun ?? MRT_SUN_C;
  const span = sun - shade;
  if (Math.abs(span) < 1e-9) return 0;
  return Math.min(1, Math.max(0, (mrtC - shade) / span));
}

/**
 * Cost multiplier for spending distance, or time, at a given mean radiant
 * temperature. 1 means no penalty.
 *
 * An unknown temperature returns 1: unsurveyed is not the same as cool, but
 * inventing a penalty for it would be worse than declining to charge one. The
 * caller is expected to report how much of a route was surveyed.
 */
export function thermalLoad(mrtC: number | null | undefined, args?: ThermalArgs): number {
  if (args && !args.heat_aware) return 1;
  if (mrtC === null || mrtC === undefined || !Number.isFinite(mrtC)) return 1;
  const inflation = args?.sun_inflation ?? SUN_INFLATION_DEFAULT;
  return 1 + inflation * exposureFraction(mrtC, args);
}

/**
 * The official UTCI thermal stress category a mean radiant temperature falls
 * in, at the reference meteorology. For labelling severity in the interface,
 * never for routing. Bröde et al. (2012), Int J Biometeorol 56(3), 481-494.
 */
export function stressCategory(mrtC: number | null | undefined): string | null {
  if (mrtC === null || mrtC === undefined || !Number.isFinite(mrtC)) return null;
  const ordered = Object.entries(UTCI_CATEGORY_MRT_C)
    .filter(([, v]) => typeof v === 'number')
    .sort((a, b) => (b[1] as number) - (a[1] as number));
  for (const [name, threshold] of ordered) {
    if (mrtC >= (threshold as number)) return name;
  }
  // Everything below the lowest reachable boundary is still at least the
  // mildest category that the reference meteorology always exceeds.
  const alwaysExceeded = Object.entries(UTCI_CATEGORY_MRT_C)
    .filter(([, v]) => v === 'always exceeded')
    .map(([name]) => name);
  return alwaysExceeded[0] ?? null;
}

/**
 * Mean and peak MRT along a routed path, weighted by edge length.
 *
 * Unsurveyed edges are excluded rather than counted as cool, and the share of
 * the route that carried data is reported alongside, so a route that is mostly
 * outside a surveyed neighbourhood cannot masquerade as a cool one.
 */
export function routeThermalStats(
  edges: Array<{ mrt?: unknown; length?: unknown }>,
): { mean_mrt_c: number | null; max_mrt_c: number | null; surveyed_share: number } {
  let weighted = 0;
  let surveyed = 0;
  let total = 0;
  let peak = -Infinity;

  for (const e of edges) {
    const len = typeof e.length === 'number' ? e.length : 0;
    total += len;
    if (typeof e.mrt !== 'number') continue;
    weighted += e.mrt * len;
    surveyed += len;
    if (e.mrt > peak) peak = e.mrt;
  }

  return {
    mean_mrt_c: surveyed > 0 ? weighted / surveyed : null,
    max_mrt_c: Number.isFinite(peak) ? peak : null,
    surveyed_share: total > 0 ? surveyed / total : 0,
  };
}

// ── subway platforms ─────────────────────────────────────────────────────────

/**
 * The radiant environment of one platform, from pipeline/thermal/stops.py.
 *
 * `tier` says how the number was arrived at, following the riprap convention:
 *   proxy       sampled from the neighbourhood MRT grid
 *   assumed     underground, where no grid applies and a constant stands in
 *   unsurveyed  open-air but outside every built neighbourhood
 *   unmodelled  the platform class is not one we classify
 */
export type PlatformThermal = {
  mrt_c: number | null;
  structure: string;
  underground: boolean | null;
  tier: 'proxy' | 'assumed' | 'unsurveyed' | 'unmodelled';
  name?: string;
};

export type StopThermalIndex = {
  get(gtfsStopId: string): PlatformThermal | undefined;
  readonly size: number;
  readonly undergroundAssumptionC: number;
};

export function makeStopThermalIndex(payload: {
  stops: Record<string, PlatformThermal>;
  underground_assumption?: { mrt_c: number };
}): StopThermalIndex {
  const map = new Map(Object.entries(payload.stops));
  return {
    get: (id) => map.get(id),
    size: map.size,
    undergroundAssumptionC: payload.underground_assumption?.mrt_c ?? 37,
  };
}

/**
 * What a wait actually costs, in thermal seconds.
 *
 * A wait has a duration and a place. Pricing it by duration alone is what
 * makes a router send a heat-vulnerable person to stand on an unshaded
 * elevated platform to save three minutes.
 *
 * NOTE ON EXTENDING THE LITERATURE. Melnikov's beta was estimated on walking,
 * not waiting, and no published study estimates a thermal penalty for standing
 * still on a transit platform. Applying the walking coefficient to a stationary
 * wait is this project's extension, and it is conservative in one respect and
 * not in another: a person waiting generates less metabolic heat than one
 * walking, but also has no prospect of leaving the exposure. It is flagged
 * rather than buried.
 */
export function thermalWaitSeconds(
  waitSeconds: number,
  platform: PlatformThermal | undefined,
  args?: ThermalArgs,
): { seconds: number; load: number; mrt_c: number | null; tier: string } {
  const mrt = platform?.mrt_c ?? null;
  const load = thermalLoad(mrt, args);
  return {
    seconds: waitSeconds * load,
    load,
    mrt_c: mrt,
    tier: platform?.tier ?? 'unmodelled',
  };
}
