"""Generate the extraction grammar from config/condition-map.yaml.

Stage 1 of the pipeline turns natural language into a profile object. The brief
for this project makes one thing non-negotiable about that step: the output is
masked at the logit level, not prompted for and then parsed. A model that is
merely asked nicely for JSON will eventually produce something else, and the
failure is silent, because a dropped constraint looks exactly like a constraint
the user never gave.

So the grammar is generated here, from the same YAML file the routing
consequences live in. The model cannot emit a condition term that
condition-map.yaml does not define, because no token sequence spelling one is
reachable. Adding a term means editing the YAML and regenerating; there is no
second place to keep in step.

The output is an EBNF string that XGrammar compiles, plus the vocabulary arrays
and a validator, written to app/src/lib/domain/profile-grammar.ts. XGrammar
ships inside @mlc-ai/web-llm, which the app already depends on, so this costs
no new runtime dependency.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

# Comfort resource categories the router can actually dispatch on. These come
# from the base app's tool schema, not from the condition map, and are listed
# here so the grammar has a single source for every enum it constrains.
RESOURCE_TYPES = [
    "cool_indoor", "warm_indoor", "bathroom", "quiet_indoor", "wifi_power",
    "shelter_24h", "pool_indoor", "seating", "linknyc", "food_pantry",
    "senior_center", "harm_reduction", "medical", "mental_health",
    "community_center",
]

HEADER = """// GENERATED by `uv run python -m pipeline.thermal.grammar`. Do not edit.
//
// The grammar that constrains stage 1 extraction, generated from
// config/condition-map.yaml. The model cannot emit a condition term this file
// does not list, because no token sequence spelling one is reachable under the
// grammar. That is the difference between a schema the model is asked to
// follow and a schema it is unable to violate.
//
// Regenerate after editing the condition map. app/tests/unit/extraction.test.ts
// asserts the two stay in step.
"""


def _quoted_alternatives(values: list[str]) -> str:
    return " | ".join(f'"\\"{v}\\""' for v in values)


def build_ebnf(conditions: list[str]) -> str:
    """EBNF for the profile object.

    Every field is required and the key order is fixed. Both are deliberate:
    a fixed order makes the output a single deterministic path through the
    grammar, and required fields mean an omitted constraint cannot be confused
    with a constraint the user did not give. Absence is spelled explicitly, as
    null or an empty array.
    """
    return f"""# Profile object. Generated; see pipeline/thermal/grammar.py
root ::= "{{" ws
  "\\"origin\\"" ws ":" ws string ws "," ws
  "\\"destination\\"" ws ":" ws nullable-string ws "," ws
  "\\"resource_types\\"" ws ":" ws resource-array ws "," ws
  "\\"conditions\\"" ws ":" ws condition-array ws "," ws
  "\\"max_minutes\\"" ws ":" ws nullable-int ws "," ws
  "\\"for_someone_else\\"" ws ":" ws boolean ws
"}}"

resource ::= {_quoted_alternatives(RESOURCE_TYPES)}
resource-array ::= "[" ws "]" | "[" ws resource (ws "," ws resource)* ws "]"

condition ::= {_quoted_alternatives(conditions)}
condition-array ::= "[" ws "]" | "[" ws condition (ws "," ws condition)* ws "]"

nullable-string ::= "null" | string
nullable-int ::= "null" | integer
boolean ::= "true" | "false"

# A place name the user typed. Free text by necessity, but still a well-formed
# JSON string: the grammar cannot know every street in New York, so the
# geocoder validates this field and the confirmation card shows what it
# resolved to before anything routes.
string ::= "\\"" char* "\\""
char ::= [^"\\\\\\x00-\\x1F] | "\\\\" ["\\\\/bfnrt]

integer ::= [1-9] [0-9]{{0,2}}

ws ::= [ \\t\\n]*
"""


def build_schema(conditions: list[str]) -> dict:
    """JSON Schema for the profile object.

    XGrammar compiles this into a grammar and masks the decoder with it, so the
    guarantee is the same as a hand-written EBNF: a condition term outside this
    enum is unreachable, not merely discouraged.

    There is deliberately no intent field. XGrammar decodes the keys in the
    order this schema declares them, so a field naming the router tool would
    be generated before destination and max_minutes, which are the only
    evidence for it. dispatch.ts derives the tool from those slots instead.

    A schema rather than EBNF because the EBNF has to be right. An earlier
    hand-written one parsed, loaded, and then had the matcher reject a sampled
    token mid-generation, which is a failure mode that only shows up against a
    real model. XGrammar generates the grammar from this instead, and the
    enums, the required list and the additionalProperties ban are the parts
    that actually carry the guarantee.
    """
    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "origin", "destination", "resource_types",
            "conditions", "max_minutes", "for_someone_else",
        ],
        "properties": {
            # Free text by necessity: the schema cannot know every street in
            # New York. The geocoder validates it and the confirmation card
            # shows what it resolved to before anything routes.
            "origin": {"type": "string"},
            "destination": {"type": ["string", "null"]},
            "resource_types": {
                "type": "array",
                "items": {"enum": RESOURCE_TYPES},
            },
            "conditions": {
                "type": "array",
                "items": {"enum": conditions},
            },
            "max_minutes": {"type": ["integer", "null"], "minimum": 1},
            "for_someone_else": {"type": "boolean"},
        },
    }


def build_ts(conditions: list[str], labels: dict[str, str], ebnf: str) -> str:
    schema = build_schema(conditions)
    return f"""{HEADER}
/**
 * The schema the decoder is masked against. XGrammar compiles it to a grammar
 * and applies it at the logit level, so a term outside these enums is
 * unreachable rather than merely discouraged.
 */
export const PROFILE_SCHEMA = {json.dumps(schema, indent=2)};

/** Serialised for web-llm's `response_format.schema`, which takes a string. */
export const PROFILE_SCHEMA_JSON = {json.dumps(json.dumps(schema))};

/**
 * The equivalent EBNF, kept for documentation and for the unit tests that
 * assert the vocabulary is exactly the condition map's. Not what ships to the
 * decoder; see PROFILE_SCHEMA.
 */
export const PROFILE_GRAMMAR = {json.dumps(ebnf)};

/** Condition vocabulary, in the order config/condition-map.yaml declares it. */
export const CONDITION_TERMS = {json.dumps(conditions, indent=2)} as const;

/** Human labels, for the confirmation card. Also from the condition map. */
export const CONDITION_LABELS: Record<string, string> = {json.dumps(labels, indent=2)};

export const RESOURCE_TYPES = {json.dumps(RESOURCE_TYPES, indent=2)} as const;

export type ConditionTerm = (typeof CONDITION_TERMS)[number];
export type ResourceType = (typeof RESOURCE_TYPES)[number];

/**
 * The profile object stage 1 produces and the confirmation card edits.
 *
 * Every field is required. An omitted constraint and a constraint the user did
 * not give must not look the same, so absence is spelled null or [].
 *
 * There is no intent field. Which of the three router tools to call is derived
 * from these slots by lib/domain/dispatch.ts, not decoded. The decoder emits
 * keys in schema order, so an intent field would have been generated before
 * the destination and the time budget it depends on: the model had to commit
 * to a classification before reading out the evidence for it, and it was wrong
 * in 65 percent of runs.
 */
export type TravelProfile = {{
  origin: string;
  destination: string | null;
  resource_types: ResourceType[];
  conditions: ConditionTerm[];
  max_minutes: number | null;
  /** True when the user is planning for somebody else ("my grandma"). */
  for_someone_else: boolean;
}};

/**
 * Validate a parsed object against the schema the grammar encodes.
 *
 * With grammar-constrained decoding this should never fail, which is the
 * point: it runs anyway, on every extraction, so that if the constrained path
 * is ever bypassed the failure is loud instead of silent.
 */
export function validateProfile(value: unknown): {{ ok: true; profile: TravelProfile }} | {{ ok: false; errors: string[] }} {{
  const errors: string[] = [];
  const v = value as Record<string, unknown>;
  if (typeof v !== 'object' || v === null) return {{ ok: false, errors: ['not an object'] }};

  if (typeof v.origin !== 'string') errors.push('origin must be a string');
  if (!(v.destination === null || typeof v.destination === 'string')) errors.push('destination must be a string or null');
  if (!Array.isArray(v.resource_types) || v.resource_types.some((r) => !RESOURCE_TYPES.includes(r as ResourceType))) {{
    errors.push(`resource_types: ${{JSON.stringify(v.resource_types)}}`);
  }}
  if (!Array.isArray(v.conditions) || v.conditions.some((cond) => !CONDITION_TERMS.includes(cond as ConditionTerm))) {{
    errors.push(`conditions: ${{JSON.stringify(v.conditions)}}`);
  }}
  if (!(v.max_minutes === null || (typeof v.max_minutes === 'number' && Number.isInteger(v.max_minutes) && v.max_minutes > 0))) {{
    errors.push(`max_minutes: ${{JSON.stringify(v.max_minutes)}}`);
  }}
  if (typeof v.for_someone_else !== 'boolean') errors.push('for_someone_else must be a boolean');

  return errors.length ? {{ ok: false, errors }} : {{ ok: true, profile: v as unknown as TravelProfile }};
}}
"""


def build_effects_ts(cmap: dict) -> str:
    """The condition map's consequences, as data the app reads.

    Generated rather than hand-copied so that config/condition-map.yaml stays
    the single place a routing consequence is written. A clinician edits the
    YAML; nobody edits this.
    """
    effects = {k: v.get("effects", {}) for k, v in cmap["vocabulary"].items()}
    return f"""{HEADER}
/** Applied when the user states nothing. The thermal layer is off. */
export const CONDITION_DEFAULTS: Record<string, unknown> = {json.dumps(cmap["defaults"], indent=2)};

/**
 * What each condition term implies for routing, from config/condition-map.yaml.
 *
 * The scale these sit on is empirical: Melnikov et al. (2022) estimate a
 * population mean sun inflation of 0.16 and individual values to 0.84. Where a
 * given condition sits on that scale is a design judgement, and the YAML says
 * so in as many words. Read a number here as "where we put this condition on a
 * measured scale", not as "what was measured for this condition".
 */
export const CONDITION_EFFECTS: Record<string, Record<string, unknown>> = {json.dumps(effects, indent=2)};

/** Version of config/condition-map.yaml these were generated from. */
export const CONDITION_MAP_VERSION = {cmap["version"]};

/** What the condition map says it does not cover. Surfaced in the interface. */
export const UNMODELLED: string[] = {json.dumps(cmap.get("unmodelled", []), indent=2)};
"""


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    cmap = yaml.safe_load((root / "config" / "condition-map.yaml").read_text())
    vocab = cmap["vocabulary"]
    conditions = list(vocab)
    labels = {k: v.get("label", k) for k, v in vocab.items()}

    ebnf = build_ebnf(conditions)
    out = root / "app" / "src" / "lib" / "domain" / "profile-grammar.ts"
    out.write_text(build_ts(conditions, labels, ebnf))

    eff = root / "app" / "src" / "lib" / "domain" / "condition-effects.ts"
    eff.write_text(build_effects_ts(cmap))

    print(f"  wrote {out.relative_to(root)}")
    print(f"  wrote {eff.relative_to(root)}")
    print(f"  {len(conditions)} condition terms, {len(RESOURCE_TYPES)} resource types")
    print(f"  grammar is {len(ebnf)} bytes, condition map v{cmap['version']}")


def demo() -> None:
    """Self-check the generated grammar's shape."""
    root = Path(__file__).resolve().parents[2]
    cmap = yaml.safe_load((root / "config" / "condition-map.yaml").read_text())
    conditions = list(cmap["vocabulary"])
    ebnf = build_ebnf(conditions)

    assert ebnf.startswith("#"), "grammar should open with a comment"
    assert "root ::=" in ebnf
    # Every vocabulary term must be reachable, and nothing else may be.
    for term in conditions:
        assert f'"\\"{term}\\""' in ebnf, f"{term} missing from the grammar"
    assert "diabetes" not in ebnf, "a term not in the condition map must not appear"
    # Every field of the profile must be constrained.
    for field in ("origin", "destination", "resource_types",
                  "conditions", "max_minutes", "for_someone_else"):
        assert f'\\"{field}\\"' in ebnf, f"{field} missing from the grammar"

    print(f"grammar.py self-check passed ({len(conditions)} terms)")


if __name__ == "__main__":
    demo()
    main()
