"""Write the thermal block of each routing profile from the derived parameters.

The three profile JSONs are data files a reviewer reads. Hand-editing three
copies of the same block invites drift, and the numbers are derived rather than
chosen, so they are generated here from thresholds.py and checked by
router/tests/thermal.rs and app/tests/unit/thermal.test.ts.
"""

from __future__ import annotations

import json
from pathlib import Path

from pipeline.thermal import thresholds as T

PROFILE_IDS = ("generic_pedestrian", "manual_wheelchair", "low_vision")
THERMAL_ARG_NAMES = ("mrt_shade", "mrt_sun", "sun_inflation")


def thermal_args(p: T.CostParameters) -> list[dict]:
    return [
        {
            "name": "mrt_shade",
            "type": "float",
            "default": p.mrt_shade_c,
            "description": (
                f"Mean radiant temperature (C) of full building shade at the reference "
                f"meteorology ({p.meteorology['label']}). The zero point of the thermal "
                f"cost: an edge at or below this pays nothing, which is also what an "
                f"unsurveyed edge pays, so the router is never paid to leave coverage."
            ),
        },
        {
            "name": "mrt_sun",
            "type": "float",
            "default": p.mrt_sun_c,
            "description": (
                "Mean radiant temperature (C) of open full sun at the same reference "
                "meteorology. Exposure is the position between the two anchors."
            ),
        },
        {
            "name": "sun_inflation",
            "type": "float",
            "default": 0.0,
            "description": (
                "Extra cost at full sun exposure, as a fraction of distance. This is "
                "beta - 1 from Melnikov et al. (2022), Sci Rep 12:2441, who estimate "
                f"a population mean beta of {T.MELNIKOV_BETA_MEAN} from 408 observed path "
                f"choices, so {round(T.MELNIKOV_BETA_MEAN - 1, 2)} means a metre in full sun feels "
                f"{int(round((T.MELNIKOV_BETA_MEAN - 1) * 100))} percent longer than a metre in shade. "
                "Defaults to 0, which switches the thermal layer off and reproduces the "
                "pre-thermal router exactly. config/condition-map.yaml sets it per person."
            ),
        },
    ]


def thermal_term(p: T.CostParameters) -> dict:
    return {
        "description": (
            "Distance-inflating coefficient on thermal exposure, after Melnikov et al. "
            "(2022). Continuous rather than banded: the UTCI stress categories are too "
            f"coarse to route on here, because dUTCI/dMRT is only {p.dutci_dmrt} at these "
            "conditions, so a whole neighbourhood falls inside one or two categories."
        ),
        "attr": "mrt",
        "from": "mrt_shade",
        "to": "mrt_sun",
        "coefficient": "sun_inflation",
    }


def write_profiles(root: Path, p: T.CostParameters) -> list[Path]:
    written = []
    for pid in PROFILE_IDS:
        path = root / "router" / "examples" / f"profile-{pid}.json"
        profile = json.loads(path.read_text())

        profile["args"] = [
            a for a in profile.get("args", [])
            if a["name"] not in THERMAL_ARG_NAMES
            and not a["name"].startswith("mrt_")
            and a["name"] != "heat_aware"
        ] + thermal_args(p)

        cost = profile["cost"]
        cost["multipliers"] = [
            m for m in cost.get("multipliers", [])
            if "heat_aware" not in json.dumps(m) and "mrt" not in json.dumps(m)
        ]
        cost["terms"] = [thermal_term(p)]

        path.write_text(json.dumps(profile, indent=2) + "\n")
        written.append(path)
    return written


TS_HEADER = """// GENERATED by `uv run python -m pipeline.thermal.profiles`. Do not edit.
//
// The thermal cost parameters, derived from published sources by
// pipeline/thermal/thresholds.py. They exist in TypeScript as well as in the
// routing profiles because transit waits are priced here, where the WASM cost
// tree never runs. app/tests/unit/thermal.test.ts asserts the two agree.
"""


def write_ts_constants(root: Path, p: T.CostParameters) -> Path:
    out = root / "app" / "src" / "lib" / "domain" / "thermal-constants.ts"
    body = f"""{TS_HEADER}
/** Mean radiant temperature (C) of full building shade at the reference meteorology. */
export const MRT_SHADE_C = {p.mrt_shade_c};

/** Mean radiant temperature (C) of open full sun at the same reference meteorology. */
export const MRT_SUN_C = {p.mrt_sun_c};

/**
 * Extra cost at full sun exposure, as a fraction of distance: beta - 1.
 *
 * Melnikov et al. (2022), Scientific Reports 12:2441, estimate a population
 * mean beta of {T.MELNIKOV_BETA_MEAN} from 408 observed pedestrian path choices.
 */
export const SUN_INFLATION_DEFAULT = {p.sun_inflation_default};

/** Melnikov et al. (2022) observed individual maximum, beta = {T.MELNIKOV_BETA_INDIVIDUAL_MAX}. */
export const SUN_INFLATION_SENSITIVE = {p.sun_inflation_sensitive};

/** Basu et al. (2024) Boston revealed preference, converted to the same units. */
export const SUN_INFLATION_BASU = {p.sun_inflation_basu_equivalent};

/** Official UTCI thermal stress boundaries, inverted to mean radiant temperature. */
export const UTCI_CATEGORY_MRT_C: Record<string, number | string> = {json.dumps(p.category_thresholds_mrt_c, indent=2)};

/** The weather every number above is conditioned on. */
export const REFERENCE_METEOROLOGY = {json.dumps(p.meteorology, indent=2)} as const;
"""
    out.write_text(body)
    return out


def main() -> None:
    from pipeline.thermal.build import HEAT_ADVISORY_MET

    root = Path(__file__).resolve().parents[2]
    p = T.derive(HEAT_ADVISORY_MET, 57.8, 202)
    T.write(root / "data", p)
    for path in write_profiles(root, p):
        print(f"  wrote {path.relative_to(root)}")
    print(f"  wrote {write_ts_constants(root, p).relative_to(root)}")
    print()
    print(T.report(p))


if __name__ == "__main__":
    main()
